export enum RouteEnum {
  BUTTON = 'button',
  TAG = 'tag',
  BADGE = 'badge',
  ALERT = 'alert',
  CALENDAR = 'calendar',
  CARD = 'card',
  CHECKBOX = 'check-box',
  COLLAPSIBLE = 'collapsible',
  INPUT = 'input',
  NAV_MENU = 'nav-menu',
  PAGINATOR = 'paginator',
  POPOVER = 'popover',
  PROGRESS_BAR = 'progress-bar',
  RADIO = 'radio',
  SCROLL_AREA = 'scroll-area',
  SELECT = 'select',
  TABS = 'tabs',
  TOAST = 'toast',
  TOOLTIP = 'tooltip',
}
